export { default as register } from "./register.js";
export { default as verifyEmail } from "./verifyEmail.js";
export { default as veriFyEmailRepeat } from "./verifyEmailRepeat.js";
export { default as googleAuth } from "./googleAuth.js";
export { default as login } from "./login.js";
export { default as logout } from "./logout.js";
export { default as updateUser } from "./updateUser.js";
export { default as current } from "./current.js";
export { default as refresch } from "./refresch.js";
